apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-02-14T12:04:58Z
  generation: 1
  labels:
    run: database
  name: database
  namespace: default
  resourceVersion: "32087"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/database
  uid: 47482e35-117f-11e8-8c84-080027034cd7
spec:
  replicas: 1
  selector:
    matchLabels:
      run: database
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: database
    spec:
      containers:
      - image: mongo:latest
        imagePullPolicy: Always
        name: database
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-02-14T12:04:58Z
    lastUpdateTime: 2018-02-14T12:04:58Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
