apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-02-14T12:04:41Z
  generation: 1
  labels:
    run: message-queue
  name: message-queue
  namespace: default
  resourceVersion: "32036"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/message-queue
  uid: 3ccfbf1f-117f-11e8-8c84-080027034cd7
spec:
  replicas: 1
  selector:
    matchLabels:
      run: message-queue
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: message-queue
    spec:
      containers:
      - image: redis:3.0-alpine
        imagePullPolicy: IfNotPresent
        name: message-queue
        ports:
        - containerPort: 6379
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-02-14T12:04:41Z
    lastUpdateTime: 2018-02-14T12:04:41Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
